/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import Core.Simuladores.Simulador;

/**
 *
 * @author UTN
 */
public class DlgAlarma extends javax.swing.JDialog {
     private Simulador simulador;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgAlarma.class.getName());

    /**
     * Creates new form DlgAlarma
     */
    public DlgAlarma(java.awt.Frame parent, boolean modal, Simulador simulador) {
        super(parent, modal);
        this.simulador = simulador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblEstadoBloqueo = new javax.swing.JLabel();
        btnBloquear = new javax.swing.JButton();
        btnDesbloquear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblEstadoPuerta = new javax.swing.JLabel();
        btnAbrir = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblEstadoAlarma = new javax.swing.JLabel();
        btnAbrochar = new javax.swing.JButton();
        btnDesabrochar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblEstadoCinturon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Cinturon");

        lblEstadoBloqueo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEstadoBloqueo.setText("Estado: Desbloqueada");

        btnBloquear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBloquear.setText("Bloquear");
        btnBloquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBloquearActionPerformed(evt);
            }
        });

        btnDesbloquear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDesbloquear.setText("Desbloquear");
        btnDesbloquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesbloquearActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Puerta");

        lblEstadoPuerta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEstadoPuerta.setText("Estado: Cerrada");

        btnAbrir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAbrir.setText("Abrir");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        btnCerrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 51, 51));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Alarma");

        lblEstadoAlarma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEstadoAlarma.setText("Estado: Inactiva");

        btnAbrochar.setText("Abrochar");
        btnAbrochar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrocharActionPerformed(evt);
            }
        });

        btnDesabrochar.setText("Desabrochar");
        btnDesabrochar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesabrocharActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Bloqueo de puerta");

        lblEstadoCinturon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEstadoCinturon.setText("Estado: Desabrochado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnAbrir)
                        .addGap(30, 30, 30)
                        .addComponent(btnCerrar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(lblEstadoBloqueo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBloquear)
                                .addGap(18, 18, 18)
                                .addComponent(btnDesbloquear)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnAbrochar)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnDesabrochar))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblEstadoCinturon)
                                    .addGap(32, 32, 32)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addGap(76, 76, 76)))))
                .addGap(51, 51, 51))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(lblEstadoPuerta))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstadoAlarma)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3)))
                .addGap(109, 109, 109))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addComponent(jLabel4)
                    .addContainerGap(294, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblEstadoBloqueo)
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnBloquear)
                                    .addComponent(btnDesbloquear)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEstadoCinturon)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAbrochar)
                                    .addComponent(btnDesabrochar))))
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEstadoPuerta))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEstadoAlarma)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar)
                    .addComponent(btnAbrir))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(jLabel4)
                    .addContainerGap(237, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBloquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBloquearActionPerformed
        simulador.getVehiculo().getPuertas().bloquear();
        lblEstadoBloqueo.setText("Estado: Bloqueada");
    }//GEN-LAST:event_btnBloquearActionPerformed

    private void btnDesbloquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesbloquearActionPerformed
        simulador.getVehiculo().getPuertas().desbloquear();
        lblEstadoBloqueo.setText("Estado: Desbloqueada");
    }//GEN-LAST:event_btnDesbloquearActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        if (!simulador.getVehiculo().getPuertas().isBloqueada()) {
            simulador.getVehiculo().getPuertas().abrir();
            lblEstadoPuerta.setText("Estado: Abierta");
            simulador.getVehiculo().getAlarma().activarAlarma();
            lblEstadoAlarma.setText("Estado: Activada");
        } else {
            lblEstadoPuerta.setText("No se puede abrir: Puerta bloqueada");
        }
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        simulador.getVehiculo().getPuertas().cerrar();
        lblEstadoPuerta.setText("Estado: Cerrada");
        simulador.getVehiculo().getAlarma().desactivarAlarma();
        lblEstadoAlarma.setText("Estado: Inactiva");
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnAbrocharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrocharActionPerformed
        if (!simulador.getVehiculo().getPuertas().isBloqueada() &&
            simulador.getVehiculo().getPuertas().isPuerta()) {

            simulador.getVehiculo().getCinturones().encender();
            lblEstadoCinturon.setText("Estado: Abrochado");
        } else {
            lblEstadoCinturon.setText("Bloqueado y cerrado");
        }
    }//GEN-LAST:event_btnAbrocharActionPerformed

    private void btnDesabrocharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesabrocharActionPerformed
        if (!simulador.getVehiculo().getPuertas().isBloqueada() &&
            simulador.getVehiculo().getPuertas().isPuerta()) {

            simulador.getVehiculo().getCinturones().apagar();
            lblEstadoCinturon.setText("Estado: Desabrochado");
        } else {
            lblEstadoCinturon.setText("Bloqueado y cerrado");
        }
    }//GEN-LAST:event_btnDesabrocharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Simulador simulador = new Simulador(); 
                DlgAlarma dialog = new DlgAlarma(new javax.swing.JFrame(), true, simulador);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnAbrochar;
    private javax.swing.JButton btnBloquear;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnDesabrochar;
    private javax.swing.JButton btnDesbloquear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEstadoAlarma;
    private javax.swing.JLabel lblEstadoBloqueo;
    private javax.swing.JLabel lblEstadoCinturon;
    private javax.swing.JLabel lblEstadoPuerta;
    // End of variables declaration//GEN-END:variables
}
