/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import Core.Simuladores.Simulador;

/**
 *
 * @author Usuario
 */
public class DlgLuces extends javax.swing.JDialog {
    private Simulador simulador;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgLuces.class.getName());

    private boolean lucesGenerales = false;
    private boolean luzAlta = false;
    private boolean luzBaja = false;
    private boolean emergencia = false;
    private boolean direccionalIzq = false;
    private boolean direccionalDer = false;
    /**
     * Creates new form MecanismoLuces
     */
    public DlgLuces(java.awt.Frame parent, boolean modal, Simulador simulador) {
        super(parent, modal);
        this.simulador = simulador;
        initComponents();
        actualizarBotones();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLuzAlta = new javax.swing.JButton();
        btnLuzBaja = new javax.swing.JButton();
        btnDireccionalIzq = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnDireccionalDer = new javax.swing.JButton();
        btnLucesEmergencia = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Apagada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLuzAlta.setText("Alta");
        btnLuzAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuzAltaActionPerformed(evt);
            }
        });
        jPanel1.add(btnLuzAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 150, -1));

        btnLuzBaja.setText("Baja");
        btnLuzBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuzBajaActionPerformed(evt);
            }
        });
        jPanel1.add(btnLuzBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 150, -1));

        btnDireccionalIzq.setText("Izquierda");
        btnDireccionalIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDireccionalIzqActionPerformed(evt);
            }
        });
        jPanel1.add(btnDireccionalIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 130, -1));

        jLabel1.setText("Direccionales");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        btnDireccionalDer.setText("Derecha");
        btnDireccionalDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDireccionalDerActionPerformed(evt);
            }
        });
        jPanel1.add(btnDireccionalDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 130, -1));

        btnLucesEmergencia.setText("Emergencia");
        btnLucesEmergencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLucesEmergenciaActionPerformed(evt);
            }
        });
        jPanel1.add(btnLucesEmergencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 200, -1));

        jLabel2.setText("Luces");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        Apagada.setText("Apagada");
        Apagada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApagadaActionPerformed(evt);
            }
        });
        jPanel1.add(Apagada, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuzAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuzAltaActionPerformed
        luzAlta = !luzAlta;
        if (luzAlta) {
            luzBaja = false; 
        }
        actualizarBotones();
// TODO add your handling code here:
    }//GEN-LAST:event_btnLuzAltaActionPerformed

    private void btnLuzBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuzBajaActionPerformed
        luzBaja = !luzBaja;
        if(luzBaja){
            luzAlta = false;
        }
        actualizarBotones();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLuzBajaActionPerformed

    private void btnLucesEmergenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLucesEmergenciaActionPerformed
        emergencia = !emergencia;
        if (emergencia) {
            direccionalIzq = false;
            direccionalDer = false;
        }
        actualizarBotones();
// TODO add your handling code here:
    }//GEN-LAST:event_btnLucesEmergenciaActionPerformed

    private void btnDireccionalIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDireccionalIzqActionPerformed
        direccionalIzq = !direccionalIzq;
        if (direccionalIzq) {
            direccionalDer = false;
            emergencia = false;
        }
        actualizarBotones();
// TODO add your handling code here:
    }//GEN-LAST:event_btnDireccionalIzqActionPerformed

    private void btnDireccionalDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDireccionalDerActionPerformed
        direccionalDer = !direccionalDer;
        if (direccionalDer) {
            direccionalIzq = false;
            emergencia = false;
        }
        actualizarBotones();
// TODO add your handling code here:
    }//GEN-LAST:event_btnDireccionalDerActionPerformed

    private void ApagadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApagadaActionPerformed
         luzAlta = false;
         luzBaja = false;
         actualizarBotones();
    }//GEN-LAST:event_ApagadaActionPerformed

    private void actualizarBotones() {
        btnLuzAlta.setText("Luz Alta: " + (luzAlta ? "ON" : "OFF"));
        btnLuzBaja.setText("Luz Baja: " + (luzBaja ? "ON" : "OFF"));
        btnLucesEmergencia.setText("Emergencia: " + (emergencia ? "ON" : "OFF"));
        btnDireccionalIzq.setText("Izquierda: " + (direccionalIzq ? "ON" : "OFF"));
        btnDireccionalDer.setText("Derecha: " + (direccionalDer ? "ON" : "OFF"));
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Simulador simulador = new Simulador(); 
                DlgLuces dialog = new DlgLuces(new javax.swing.JFrame(), true, simulador);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apagada;
    private javax.swing.JButton btnDireccionalDer;
    private javax.swing.JButton btnDireccionalIzq;
    private javax.swing.JButton btnLucesEmergencia;
    private javax.swing.JButton btnLuzAlta;
    private javax.swing.JButton btnLuzBaja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}