/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

/**
 *
 * @author Usuario
 */
public class MecanismoLuces extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MecanismoLuces.class.getName());

    private boolean lucesGenerales = false;
    private boolean luzAlta = false;
    private boolean luzBaja = false;
    private boolean emergencia = false;
    private boolean direccionalIzq = false;
    private boolean direccionalDer = false;
    /**
     * Creates new form MecanismoLuces
     */
    public MecanismoLuces(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        actualizarBotones();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnLucesGenerales = new javax.swing.JButton();
        btnLuzAlta = new javax.swing.JButton();
        btnLuzBaja = new javax.swing.JButton();
        btnLucesEmergencia = new javax.swing.JButton();
        btnDireccionalIzq = new javax.swing.JButton();
        btnDireccionalDer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        btnLucesGenerales.setText("LucesGenerales");
        btnLucesGenerales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLucesGeneralesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 14, 0, 64);
        getContentPane().add(btnLucesGenerales, gridBagConstraints);

        btnLuzAlta.setText("Alta");
        btnLuzAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuzAltaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 39;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 12, 0, 0);
        getContentPane().add(btnLuzAlta, gridBagConstraints);

        btnLuzBaja.setText("Baja");
        btnLuzBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuzBajaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 39;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        getContentPane().add(btnLuzBaja, gridBagConstraints);

        btnLucesEmergencia.setText("Emergencia");
        btnLucesEmergencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLucesEmergenciaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 14, 0, 64);
        getContentPane().add(btnLucesEmergencia, gridBagConstraints);

        btnDireccionalIzq.setText("Izquierda");
        btnDireccionalIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDireccionalIzqActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 12, 179, 0);
        getContentPane().add(btnDireccionalIzq, gridBagConstraints);

        btnDireccionalDer.setText("Derecha");
        btnDireccionalDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDireccionalDerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 38;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 14, 179, 64);
        getContentPane().add(btnDireccionalDer, gridBagConstraints);

        jLabel1.setText("Direccionales");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("Luces");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 35, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuzAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuzAltaActionPerformed
        luzAlta = !luzAlta;
        if (luzAlta) {
            luzBaja = false; 
        }
        actualizarBotones();
// TODO add your handling code here:
    }//GEN-LAST:event_btnLuzAltaActionPerformed

    private void btnLuzBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuzBajaActionPerformed
        luzBaja = !luzBaja;
        if(luzBaja){
            luzAlta = false;
        }
        actualizarBotones();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLuzBajaActionPerformed

    private void btnLucesGeneralesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLucesGeneralesActionPerformed
        lucesGenerales = !lucesGenerales;
        actualizarBotones();
// TODO add your handling code here:
    }//GEN-LAST:event_btnLucesGeneralesActionPerformed

    private void btnLucesEmergenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLucesEmergenciaActionPerformed
        emergencia = !emergencia;
        if (emergencia) {
            direccionalIzq = false;
            direccionalDer = false;
        }
        actualizarBotones();
// TODO add your handling code here:
    }//GEN-LAST:event_btnLucesEmergenciaActionPerformed

    private void btnDireccionalIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDireccionalIzqActionPerformed
        direccionalIzq = !direccionalIzq;
        if (direccionalIzq) {
            direccionalDer = false;
            emergencia = false;
        }
        actualizarBotones();
// TODO add your handling code here:
    }//GEN-LAST:event_btnDireccionalIzqActionPerformed

    private void btnDireccionalDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDireccionalDerActionPerformed
        direccionalDer = !direccionalDer;
        if (direccionalDer) {
            direccionalIzq = false;
            emergencia = false;
        }
        actualizarBotones();
// TODO add your handling code here:
    }//GEN-LAST:event_btnDireccionalDerActionPerformed

    private void actualizarBotones() {
        btnLucesGenerales.setText("Luces Generales: " + (lucesGenerales ? "ON" : "OFF"));
        btnLuzAlta.setText("Luz Alta: " + (luzAlta ? "ON" : "OFF"));
        btnLuzBaja.setText("Luz Baja: " + (luzBaja ? "ON" : "OFF"));
        btnLucesEmergencia.setText("Emergencia: " + (emergencia ? "ON" : "OFF"));
        btnDireccionalIzq.setText("Izquierda: " + (direccionalIzq ? "ON" : "OFF"));
        btnDireccionalDer.setText("Derecha: " + (direccionalDer ? "ON" : "OFF"));
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MecanismoLuces dialog = new MecanismoLuces(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDireccionalDer;
    private javax.swing.JButton btnDireccionalIzq;
    private javax.swing.JButton btnLucesEmergencia;
    private javax.swing.JButton btnLucesGenerales;
    private javax.swing.JButton btnLuzAlta;
    private javax.swing.JButton btnLuzBaja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
    
}