/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import Core.Simuladores.Simulador;
import Subsistemas.Limpiaparabrisas.ParabrisasVelocidad;
import java.util.HashSet;

/**
 *
 * @author UTN
 */
public class DlgLimpiaparabrisas extends javax.swing.JDialog {
    private Simulador simulador;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgLimpiaparabrisas.class.getName());

    /**
     * Creates new form DlgLimpiaparabrisas
     */
    public DlgLimpiaparabrisas(java.awt.Frame parent, boolean modal, Simulador simulador) {
        super(parent, modal);
        this.simulador = simulador;
        initComponents();
        
    ParabrisasVelocidad estado = simulador.getVehiculo().getLimpiaparabrisas().getVelocidadActual();
    switch (estado) {
        case BAJA:
            btnBaja.setSelected(true);
            break;
        case MEDIA:
            btnMedia.setSelected(true);
            break;
        case ALTA:
            btnAlta.setSelected(true);
            break;
        case APAGADA:
        default:
            btnApagado.setSelected(true);
            break;
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRadioBoton = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnApagado = new javax.swing.JRadioButton();
        btnBaja = new javax.swing.JRadioButton();
        btnMedia = new javax.swing.JRadioButton();
        btnAlta = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btnRadioBoton.add(btnApagado);
        btnApagado.setSelected(true);
        btnApagado.setText("APAGADO");
        btnApagado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagadoActionPerformed(evt);
            }
        });

        btnRadioBoton.add(btnBaja);
        btnBaja.setText("BAJA");
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });

        btnRadioBoton.add(btnMedia);
        btnMedia.setText("MEDIA");
        btnMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediaActionPerformed(evt);
            }
        });

        btnRadioBoton.add(btnAlta);
        btnAlta.setText("ALTA");
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Estados Limpiaparabrisas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnApagado)
                        .addGap(31, 31, 31)
                        .addComponent(btnBaja)
                        .addGap(38, 38, 38)
                        .addComponent(btnMedia)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnAlta)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlta)
                    .addComponent(btnMedia)
                    .addComponent(btnBaja)
                    .addComponent(btnApagado))
                .addGap(0, 76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApagadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagadoActionPerformed
        simulador.getVehiculo().getLimpiaparabrisas().detener();
        
    }//GEN-LAST:event_btnApagadoActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
        simulador.getVehiculo().getLimpiaparabrisas().cambiarVelocidad(ParabrisasVelocidad.BAJA);
    }//GEN-LAST:event_btnBajaActionPerformed

    private void btnMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediaActionPerformed
        simulador.getVehiculo().getLimpiaparabrisas().cambiarVelocidad(ParabrisasVelocidad.MEDIA);
    }//GEN-LAST:event_btnMediaActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        simulador.getVehiculo().getLimpiaparabrisas().cambiarVelocidad(ParabrisasVelocidad.ALTA);
    }//GEN-LAST:event_btnAltaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Simulador simulador = new Simulador(); 
                DlgLimpiaparabrisas dialog = new DlgLimpiaparabrisas(new javax.swing.JFrame(), true, simulador);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAlta;
    private javax.swing.JRadioButton btnApagado;
    private javax.swing.JRadioButton btnBaja;
    private javax.swing.JRadioButton btnMedia;
    private javax.swing.ButtonGroup btnRadioBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
